version: '2'
services:
  drupal:
    image: drupal
    ports:
      - '8080:80'
    volumes:
      - 'drupal-modules:/var/www/html/modules'
      - 'drupal-profiles:/var/www/html/profiles'
      - 'drupal-sites:/var/www/html/sites'
      - 'drupal-themes:/var/www/html/themes'
  psql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  drupal-modules: null
  drupal-profiles: null
  drupal-sites: null
  drupal-themes: null
